from building import *

# The set of source files associated with this SConscript file.
cwd = GetCurrentDir()
src     = Glob('*.S')
src     += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('SpacemitPlatformDef', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

